services:
    contao_author.controller.module_author:
        class: Dreibein\ContaoAuthorBundle\Controller\FrontendModule\AuthorController
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.frontend_module, category: news }

    contao_author.data_container.user:
        class: Dreibein\ContaoAuthorBundle\DataContainer\User
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.callback, target: config.onload, table: tl_user, method: modifyPalette }
